const INVALID_SESSION = 'Invalid session'
const DEFAULT_TOKEN_DURATION = 60 * 30 // NOTE: Half an hour
const DEFAULT_SESSION_DURATION = 24 * 60 * 60 * 1000 // 24 hours

module.exports = {
  INVALID_SESSION,
  DEFAULT_TOKEN_DURATION,
  DEFAULT_SESSION_DURATION,
}
