name: CI

on:
  push:
    branches:
      - '**'

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: ${{ (github.ref != format('refs/heads/{0}', github.event.repository.default_branch)) }}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:16

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run tests
      run: |
        yarn install
        yarn test
