name: CI

on:
  push:
    branches:
      - '**'

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: ${{ (github.ref != format('refs/heads/{0}', github.event.repository.default_branch)) }}

jobs:
  test:
    runs-on: ubuntu-latest
    # nuxt@4 requires ^22.12.0 || ^24.11.0, and a transitive @babel/generator
    # requires ^22.18.0 || >=24.11.0.
    container:
      image: node:24

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install
      run: yarn install --frozen-lockfile

    - name: Test
      run: yarn test
